# -*- coding: utf-8 -*-
#公用配置
DEBUG = False
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ENCODING = "utf8mb4"
SECRET_KEY = "12DJFIDF"


DOMAIN = {
    "www":"http://127.0.0.1:3000"
}

AUTH_COOKIE_NAME = "coolmovie"

DEBUG_TB_INTERCEPT_REDIRECTS = False